// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rejotfqiomtyjjdbkchj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlam90ZnFpb210eWpqZGJrY2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjIzMDcsImV4cCI6MjA3MjMzODMwN30.7TEqPykyjIOKClva7EuyRjRTMFw3XLcc3v3YoS2Qepg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});